/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated.staff'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated.ops'
import { Route as AuthenticatedFanRouteImport } from './routes/_authenticated.fan'
import { Route as ApiPublicTickRouteImport } from './routes/api/public/tick'
import { Route as ApiAuthGoogleExchangeRouteImport } from './routes/api/auth/google/exchange'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFanRoute = AuthenticatedFanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicTickRoute = ApiPublicTickRouteImport.update({
  id: '/api/public/tick',
  path: '/api/public/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleExchangeRoute = ApiAuthGoogleExchangeRouteImport.update({
  id: '/api/auth/google/exchange',
  path: '/api/auth/google/exchange',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fan': typeof AuthenticatedFanRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/auth/google/exchange': typeof ApiAuthGoogleExchangeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fan': typeof AuthenticatedFanRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/auth/google/exchange': typeof ApiAuthGoogleExchangeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/fan': typeof AuthenticatedFanRoute
  '/_authenticated/ops': typeof AuthenticatedOpsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/tick': typeof ApiPublicTickRoute
  '/api/auth/google/exchange': typeof ApiAuthGoogleExchangeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fan'
    | '/ops'
    | '/staff'
    | '/api/chat'
    | '/api/public/tick'
    | '/api/auth/google/exchange'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fan'
    | '/ops'
    | '/staff'
    | '/api/chat'
    | '/api/public/tick'
    | '/api/auth/google/exchange'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/fan'
    | '/_authenticated/ops'
    | '/_authenticated/staff'
    | '/api/chat'
    | '/api/public/tick'
    | '/api/auth/google/exchange'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicTickRoute: typeof ApiPublicTickRoute
  ApiAuthGoogleExchangeRoute: typeof ApiAuthGoogleExchangeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fan': {
      id: '/_authenticated/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof AuthenticatedFanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/tick': {
      id: '/api/public/tick'
      path: '/api/public/tick'
      fullPath: '/api/public/tick'
      preLoaderRoute: typeof ApiPublicTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/exchange': {
      id: '/api/auth/google/exchange'
      path: '/api/auth/google/exchange'
      fullPath: '/api/auth/google/exchange'
      preLoaderRoute: typeof ApiAuthGoogleExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFanRoute: typeof AuthenticatedFanRoute
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFanRoute: AuthenticatedFanRoute,
  AuthenticatedOpsRoute: AuthenticatedOpsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicTickRoute: ApiPublicTickRoute,
  ApiAuthGoogleExchangeRoute: ApiAuthGoogleExchangeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
